name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ecommerce-api .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 ecommerce-api

      - name: Check app
        run: curl http://localhost:3000 || true